# -*- coding: utf-8 -*-
"""Training using Siamese network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bsH2u6CPk-xYcAnjS5AeQQQLMyb2xT8l
"""

import numpy as np 
import pandas as pd 
import os
import gc

import matplotlib.pyplot as plt
import matplotlib.image as mplimg
from matplotlib.pyplot import imshow

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

from keras import layers
from keras.preprocessing import image
from keras.applications.imagenet_utils import preprocess_input
from keras.layers import Input, Dense, Activation, BatchNormalization, Flatten, Conv2D
from keras.layers import AveragePooling2D, MaxPooling2D, Dropout
from keras.models import Model, load_model

import keras.backend as K
from keras.models import Sequential

import warnings
warnings.simplefilter("ignore", category=DeprecationWarning)

train_df = pd.read_csv("input/no_new.csv")
train_df.head()

# Loading input data from https://www.kaggle.com/pestipeti/keras-cnn-starter/
def prepareImages(data, m, dataset):
    print("Preparing images")
    X_train = np.zeros((m, 100, 100, 3))
    count = 0
    
    for fig in data['Image']:
        #load images into images of size 100x100x3
        try:
            img = image.load_img("input/"+dataset+"/"+fig, target_size=(100, 100, 3))
            x = image.img_to_array(img)
            x = preprocess_input(x)

            X_train[count] = x
            if (count%500 == 0):
               print("Processing image: ", count+1, ", ", fig)
            count += 1
        except:
            pass

    return X_train

"""Prepare the labels helper function"""

def prepare_labels(y):
    values = np.array(y)
    label_encoder = LabelEncoder()
    integer_encoded = label_encoder.fit_transform(values)
    # print(integer_encoded)

    onehot_encoder = OneHotEncoder(sparse=False)
    integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
    # print(onehot_encoded)

    y = onehot_encoded
    # print(y.shape)
    return y, label_encoder, onehot_encoder

"""Prepare images for training data"""

X = prepareImages(train_df[12000:], train_df[12000:].shape[0], "train")

X /= 255

y, label_encoder, ohe = prepare_labels(train_df[12000:]['Id'])
y_test, label_encoder_new, ohe_new = prepare_labels(train_df[12000:]['Id'])

#y = np.pad(y, (0, 4097 - len(y)), 'constant')

model = load_model('model.h5')
correct = 0
incorrect = 0

predictions = model.predict(np.array(X), verbose=1)

for x, y_new in zip(predictions, y_test):
    l_1 = ohe.inverse_transform(y[np.argmax(x)].reshape(1, -1))
    l_1 = label_encoder.inverse_transform(np.ravel([[int(l_1)]]))
    l_2 = ohe_new.inverse_transform(y_new.reshape(1, -1))
    l_2 = label_encoder.inverse_transform(np.ravel([[int(l_2)]]))
    if(l_1 == l_2):
        correct += 1
        print("Correct for image:" + l_1)
    else:
        incorrect += 1

print("Correct ", correct)
print("Incorrect ", incorrect)